#!/usr/bin/python3
import psycopg2, login
import cgi
import html

form = cgi.FieldStorage()

product_sku = form.getvalue("sku")

print("Content-Type: text/html\n")
print("<!DOCTYPE html>")
print('<html lang="en">')
print("  <head>")
print("    <title>My Web Page</title>")
print('    <link rel="stylesheet" href="./styles3.css" />')
print("  </head>")
print("  <body>")
print('    <div class="sidebar">')
print('      <a href="Home.html">Home</a>')
print('      <a href="ManageProducts.html" class="white-link">Products</a>')
print('      <a href="ManageSuppliers.html">Suppliers</a>')
print('      <a href="ManageCustomers.html">Customers</a>')
print("    </div>")
print('    <div class="content">')
print("      <h1>Edit Product SKU - {}</h1>".format(product_sku))
print('      <div class="boxes">')
print('        <div class="box">')
print('          <div class="box-text">')
print('            <img src="./icons/euro.png" />')
print("            <p>Alter</p>")
print("            <p>Price</p>")
print("          </div>")
print("         <form id='myForm' action='AlterPrice.cgi' method='POST'>")
print("     <input type='hidden' name='product_sku' value='{}'>".format(product_sku))
print(
    '          <button class="box-btn" onclick="location.href=\'AlterPrice.html\'"></button>'
)
print("        </form>")
print("        </div>")
print('        <div class="box">')
print('          <div class="box-text">')
print('            <img src="./icons/book.png" />')
print("            <p>Alter</p>")
print("            <p>Description</p>")
print("          </div>")
print("         <form id='myForm' action='AlterDescription.cgi' method='POST'>")
print("     <input type='hidden' name='product_sku' value='{}'>".format(product_sku))
print('          <button class="box-btn"></button>')
print("        </form>")
print("        </div>")
print("      </div>")
print("    </div>")
print("  </body>")
print("</html>")
