#!/usr/bin/python3

import psycopg2, cgi
import login
import html

form = cgi.FieldStorage()
value = form.getvalue("customer")

print("Content-Type: text/html\n")
print("<!DOCTYPE html>")
print("<html lang='en'>")
print("  <head>")
print("    <title>My Web Page</title>")
print("    <link rel='stylesheet' href='./styles.css' />")
print("         <form id='myForm' action='PayOrder.cgi' method='POST'>")
print(
    "     <input type='hidden' name='customer' value='{}'>".format(html.escape(value))
)
print("         <form id='myForm' action='PlaceOrder.cgi' method='POST'>")
print(
    "     <input type='hidden' name='customer' value='{}'>".format(html.escape(value))
)
print("         </form>")
print("         </form>")
print("  </head>")
print("  <body>")
print("    <div class='sidebar'>")
print("      <a href='Home.html'>Home</a>")
print("      <a href='Orders.html' class='white-link'>Orders</a>")
print("    </div>")
print("    <div class='content'>")
print("      <h1>Orders</h1>")
print("      <div class='boxes'>")
print("        <a href='SelectOrder.cgi' class='box-link'>")
print("          <div class='box'>")
print("            <div class='box-text'>")
print("              <img src='./icons/box.png' />")
print("              <p>Place</p>")
print("              <p>Order</p>")
print("            </div>")
print("          </div>")
print("        </a>")
print("        <a href='ConsultOrders.html' class='box-link'>")
print("          <div class='box'>")
print("            <div class='box-text'>")
print("              <img src='./icons/lupaBranca.png' />")
print("              <p>Consult</p>")
print("              <p>Orders</p>")
print("            </div>")
print("          </div>")
print("        </a>")
print("      </div>")
print("    </div>")
print("  </body>")
print("</html>")
