#!/usr/bin/python3

import psycopg2, cgi
import login
import html

form = cgi.FieldStorage()
customer = form.getvalue("customer")

print("Content-Type: text/html\n")
print("<!DOCTYPE html>")
print("<html lang='en'>")
print("  <head>")
print("    <title>My Web Page</title>")
print("    <link rel='stylesheet' href='./styles.css' />")
print("         <form id='myForm' action='PayOrder.cgi' method='POST'>")
print(
    "     <input type='hidden' name='customer' value='{}'>".format(html.escape(customer))
)
print("         <form id='myForm' action='PlaceOrder.cgi' method='POST'>")
print(
    "     <input type='hidden' name='customer' value='{}'>".format(html.escape(customer))
)
print("         </form>")
print("         </form>")
print("  </head>")
print("  <body>")
print("    <div class='sidebar'>")
print("      <a href='Home.html'>Home</a>")
print("      <a href='Orders.html' class='white-link'>Orders</a>")
print("    </div>")
print("    <div class='content'>")
print("      <h1>Orders</h1>")
print('      <div class="boxes">')
print('        <div class="box">')
print('          <div class="box-text">')
print('            <img src="./icons/euro.png" />')
print('            <p>Alter</p>')
print('            <p>Price</p>')
print('          </div>')
print("         <form id='myForm' action='SelectOrder.cgi' method='POST'>")
print(
    "     <input type='hidden' name='product_sku' value='{}'>".format(html.escape(customer))
)
print('          <button class="box-btn" onclick="location.href=\'AlterPrice.html\'"></button>')
print('        </form>')
print('        </div>')
print("        <a href='SelectOrder.cgi' class='box-link'>")
print("          <div class='box'>")
print("            <div class='box-text'>")
print("              <img src='./icons/lupaBranca.png'")
print('                   style="width: 67px; height: 67px"')
print('              />')
print("              <p>Consult</p>")
print("              <p>Orders</p>")
print("            </div>")
print("          </div>")
print("        </a>")
print("      </div>")
print("    </div>")
print("  </body>")
print("</html>")
