#!/usr/bin/python3
import psycopg2, login
import cgi
import html

form = cgi.FieldStorage()

customer = form.getvalue("customer")

print("Content-Type: text/html\n")
print("<!DOCTYPE html>")
print('<html lang="en">')
print("  <head>")
print("    <title>My Web Page</title>")
print('    <link rel="stylesheet" href="./styles3.css" />')
print("  </head>")
print("  <body>")
print('    <div class="sidebar">')
print('      <a href="Home.html">Home</a>')
print("      <form action='Orders.cgi' method='POST'>")
print("        <input type='hidden' name='customer' value='{}'>".format(customer))
print("        <button type='submit' class='btn-a white-link'>Orders</button>")
print("      </form>")
print("    </div>")
print('    <div class="content">')
print("      <h1>Orders</h1>")
print('      <div class="boxes">')
print('        <div class="box">')
print('          <div class="box-text">')
print('            <img src="./icons/box.png" />')
print("            <p>Place</p>")
print("            <p>Order</p>")
print("          </div>")
print("         <form action='PlaceOrder.cgi' method='POST'>")
print("     <input type='hidden' name='customer' value='{}'>".format(customer))
print('          <button class="box-btn"></button>')
print("        </form>")
print("        </div>")
print('        <div class="box">')
print('          <div class="box-text">')
print(
    '            <img src="./icons/lupaBranca.png" style="width: 67px; height: 67px;" />'
)
print("            <p>Consult</p>")
print("            <p>Orders</p>")
print("          </div>")
print("         <form action='ConsultOrders.cgi' method='POST'>")
print("     <input type='hidden' name='customer' value='{}'>".format(customer))
print('          <button class="box-btn"></button>')
print("        </form>")
print("        </div>")
print("      </div>")
print("    </div>")
print("  </body>")
print("</html>")
